version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - MONGO_URI=uri
      - JWT_SECRET=secret
      - RAZORPAY_KEY_ID=rzpkey
      - RAZORPAY_KEY_SECRET=rzpsecret
    volumes:
      - ./backend:/app
    restart: unless-stopped

  frontend:
    build: .
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - REACT_APP_BACKEND_URL=your-backend-url
      - REACT_APP_RAZORPAY_KEY_ID=your-razorpay-key-id
    restart: unless-stopped